import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { AgentImage, AgentVideo, AgentId } from '@/types';
import { stripHandoff } from './MarkdownRenderer';
import styles from '../WorkspaceFeed.module.css';

export interface VisualRendererProps {
  output: string;
  agentId: AgentId;
  agentImages: AgentImage[];
  agentVideos: AgentVideo[];
  isRunning: boolean;
}

/**
 * 专为 Visual (美术指导) Agent 设计的渲染器，
 * 除了支持 Markdown 外，还会在文本下方挂载图片网格视图与视频组件。
 */
export function VisualRenderer({
  output,
  agentId,
  agentImages,
  agentVideos,
  isRunning,
}: VisualRendererProps) {
  if (!output && isRunning) {
    return (
      <div className={`${styles.cardOutput} markdown-body`}>
        <div className={styles.thinking}>
          <span className={styles.thinkingDot} />
          <span className={styles.thinkingDot} />
          <span className={styles.thinkingDot} />
        </div>
      </div>
    );
  }

  const myImages = agentImages.filter((img) => img.agentId === agentId);
  const myVideos = agentVideos.filter((vid) => vid.agentId === agentId);

  return (
    <div className={`${styles.cardOutput} markdown-body`}>
      {output ? (
        <>
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{stripHandoff(output)}</ReactMarkdown>
          
          {myImages.length > 0 && (
            <div className={styles.agentImagesContainer}>
              {myImages.map((img, idx) => (
                <img key={idx} src={img.dataUrl} alt={`Generated by ${agentId}`} className={styles.agentImage} />
              ))}
            </div>
          )}

          {myVideos.length > 0 && (
            <div className={styles.agentVideosContainer}>
              {myVideos.map((vid, idx) => (
                <video
                  key={idx}
                  src={vid.dataUrl}
                  controls
                  className={styles.agentVideo}
                  poster={myImages[0]?.dataUrl}
                />
              ))}
            </div>
          )}
        </>
      ) : (
        <span style={{ color: 'var(--text-muted)', fontSize: '13px' }}>—</span>
      )}
    </div>
  );
}
